// 角色BP流程（完全按你的顺序）
const ROLE_BP_ORDER = [
    "蓝ban角色",
    "红ban角色",
    "红ban角色",
    "蓝ban角色",
    "蓝pick角色",
    "红pick角色",
    "红pick角色",
    "蓝pick角色",
    "蓝pick角色",
    "红pick角色"
];

// 贝壳能力BP流程
const SKILL_BP_ORDER = [
    "红ban贝壳",
    "蓝ban贝壳",
    "红选贝壳",
    "蓝选贝壳",
    "蓝选贝壳",
    "红选贝壳",
    "红选贝壳",
    "蓝选贝壳"
];

// 角色池
const ROLE_LIST = [
    {id:1,name:"艾尼路",img:"anl.png"},
    {id:2,name:"艾斯",img:"as.png"},
    {id:4,name:"大熊",img:"dx.png"},
    {id:5,name:"黑胡子",img:"hhz.png"},
    {id:6,name:"黄猿",img:"hy.png"},
    {id:7,name:"卡普",img:"kp.png"},
    {id:8,name:"莫利亚",img:"mly.png"},
    {id:9,name:"麦哲伦",img:"mzl.png"},
    {id:10,name:"女帝",img:"nd.png"},
    {id:11,name:"青雉",img:"qz.png"},
    {id:12,name:"沙鳄鱼",img:"sey.png"},
    {id:13,name:"伊娃科夫",img:"ywkf.png"},
    {id:14,name:"鹰眼",img:"yy.png"},
    {id:15,name:"战国",img:"zg.png"},
    // ===== 金卡 =====
    {id:16,name:"阿保",img:"ab.png"},
    {id:17,name:"阿龙",img:"al.png"},
    {id:18,name:"巴基",img:"bj.png"},
    {id:19,name:"波尼",img:"bn.png"},
    {id:20,name:"德雷克",img:"dlk.png"},
    {id:21,name:"弗兰奇",img:"flq.png"},
    {id:22,name:"杰布拉",img:"jbl.png"},
    {id:23,name:"狙击王",img:"jjw.png"},
    {id:24,name:"基拉",img:"jl.png"},
    {id:25,name:"卡古",img:"kg.png"},
    {id:26,name:"克里克",img:"klk.png"},
    {id:27,name:"罗宾",img:"lb.png"},
    {id:28,name:"龙马",img:"lm.png"},
    {id:29,name:"mr1",img:"mr1.png"},
    {id:30,name:"佩罗娜",img:"pln.png"},
    {id:31,name:"全周日",img:"qzr.png"},
    {id:32,name:"日奈",img:"rn.png"},
    {id:33,name:"司法岛路飞",img:"sfdlf.png"},
    {id:34,name:"司法岛娜美",img:"sfdnm.png"},
    {id:35,name:"司法岛乔巴",img:"sfdqb.png"},
    {id:36,name:"司法岛山治",img:"sfdsz.png"},
    {id:37,name:"四神官",img:"ssg.png"},
    {id:38,name:"瓦波尔",img:"wbe.png"},
    {id:39,name:"瓦帕",img:"wp.png"},
    {id:40,name:"鼯鼠",img:"ws.png"},
    {id:41,name:"小冯",img:"xf.png"},
    {id:42,name:"烟鬼",img:"yg.png"},
    // ===== 紫卡 =====
    {id:43,name:"艾比达",img:"abd.png"},
    {id:44,name:"阿布萨罗姆",img:"abslm.png"},
    {id:45,name:"阿金",img:"aj.png"},
    {id:46,name:"波尔西",img:"bex.png"},
    {id:47,name:"巴利",img:"bl.png"},
    {id:48,name:"贝拉米",img:"blm.png"},
    {id:49,name:"长环岛路飞",img:"chdlf.png"},
    {id:50,name:"多尔顿",img:"ded.png"},
    {id:51,name:"二指",img:"ez.png"},
    {id:52,name:"福克西",img:"fkx.png"},
    {id:53,name:"甘福尔",img:"gfe.png"},
    {id:54,name:"盖蒙",img:"gm.png"},
    {id:55,name:"霍古巴克",img:"hgbk.png"},
    {id:56,name:"佳妮法",img:"jnf.png"},
    {id:57,name:"卡巴奇",img:"kbq.png"},
    {id:58,name:"克洛",img:"kl.png"},
    {id:59,name:"路飞",img:"lf.png"},
    {id:60,name:"里奇船长",img:"lqcz.png"},
    {id:61,name:"mr3",img:"mr3.png"},
    {id:62,name:"mr5",img:"mr5.png"},
    {id:63,name:"娜美",img:"nm.png"},
    {id:64,name:"佩鲁恰卡",img:"plqk.png"},
    {id:65,name:"乔巴",img:"qb.png"},
    {id:66,name:"情人节",img:"qrj.png"},
    {id:67,name:"萨蒂",img:"sd.png"},
    {id:68,name:"圣诞节",img:"sdj.png"},
    {id:69,name:"索隆",img:"sl.png"},
    {id:70,name:"山治",img:"sz.png"},
    {id:71,name:"塔希米",img:"txm.png"},
    {id:72,name:"乌索普",img:"wsp.png"},
    {id:73,name:"薇薇",img:"ww.png"},
    {id:74,name:"小八",img:"xb.png"},
    {id:75,name:"小红发",img:"xhf.png"}
];

// 贝壳能力池
const SKILL_LIST = [
    {id:1,name:"霸王色",img:"bws.png"},
    {id:2,name:"武装色",img:"wzs.png"},
    {id:3,name:"见闻色",img:"jws.png"},
    {id:4,name:"闪光贝",img:"sgb.png"},
    {id:5,name:"喷风贝",img:"pfb.png"},
    {id:6,name:"斩击贝",img:"zjb.png"},
    {id:7,name:"雷光贝",img:"lgb.png"},
    {id:8,name:"烈焰贝",img:"lyb.png"},
    {id:9,name:"疾风贝",img:"jfb.png"},
    {id:10,name:"助力音贝",img:"zlyb.png"},
    {id:11,name:"鼓舞音贝",img:"gwyb.png"},
    {id:12,name:"冲击贝",img:"cjb.png"},
    {id:13,name:"影像贝",img:"yxb.png"},
    {id:14,name:"护体炎贝",img:"htyb.png"},
    {id:15,name:"爆炎贝",img:"byb.png"},
    {id:16,name:"炫光贝",img:"xgb.png"},
    {id:17,name:"酸液贝",img:"syb.png"},
    {id:18,name:"轰轰贝",img:"hhb.png"},
    {id:19,name:"振奋音贝",img:"zfyb.png"},
    {id:20,name:"强击贝",img:"qjb.png"},
    {id:21,name:"旋风贝",img:"xfb.png"},
    {id:22,name:"雾炮贝",img:"wpb.png"},
    {id:23,name:"冻冻贝",img:"ddb.png"},
    {id:24,name:"斥空贝",img:"ckb.png"},
    {id:25,name:"冷雾贝",img:"lwb.png"},
    {id:26,name:"瓦斯贝",img:"wsb.png"},
    {id:27,name:"球云贝",img:"qyb.png"},
    {id:28,name:"震级贝",img:"zhenjibei.png"}
]
// 援护池（红蓝可重复选取，单方内部不可重复）
const SUPPORT_LIST = [
    {id:1,name:"艾尼路",img:"anl.png"},
    {id:2,name:"艾斯",img:"as.png"},
    {id:4,name:"大熊",img:"dx.png"},
    {id:5,name:"黑胡子",img:"hhz.png"},
    {id:6,name:"黄猿",img:"hy.png"},
    {id:7,name:"卡普",img:"kp.png"},
    {id:8,name:"莫利亚",img:"mly.png"},
    {id:9,name:"麦哲伦",img:"mzl.png"},
    {id:10,name:"女帝",img:"nd.png"},
    {id:11,name:"青雉",img:"qz.png"},
    {id:12,name:"沙鳄鱼",img:"sey.png"},
    {id:13,name:"伊娃科夫",img:"ywkf.png"},
    {id:14,name:"鹰眼",img:"yy.png"},
    // ===== 金卡 =====
    {id:16,name:"阿保",img:"ab.png"},
    {id:17,name:"阿龙",img:"al.png"},
    {id:18,name:"巴基",img:"bj.png"},
    {id:19,name:"波尼",img:"bn.png"},
    {id:20,name:"德雷克",img:"dlk.png"},
    {id:21,name:"弗兰奇",img:"flq.png"},
    {id:22,name:"杰布拉",img:"jbl.png"},
    {id:23,name:"狙击王",img:"jjw.png"},
    {id:24,name:"基拉",img:"jl.png"},
    {id:25,name:"卡古",img:"kg.png"},
    {id:26,name:"克里克",img:"klk.png"},
    {id:27,name:"罗宾",img:"lb.png"},
    {id:28,name:"龙马",img:"lm.png"},
    {id:29,name:"mr1",img:"mr1.png"},
    {id:30,name:"佩罗娜",img:"pln.png"},
    {id:31,name:"全周日",img:"qzr.png"},
    {id:32,name:"日奈",img:"rn.png"},
    {id:33,name:"司法岛路飞",img:"sfdlf.png"},
    {id:34,name:"司法岛娜美",img:"sfdnm.png"},
    {id:35,name:"司法岛乔巴",img:"sfdqb.png"},
    {id:36,name:"司法岛山治",img:"sfdsz.png"},
    {id:37,name:"四神官",img:"ssg.png"},
    {id:38,name:"瓦波尔",img:"wbe.png"},
    {id:39,name:"瓦帕",img:"wp.png"},
    {id:40,name:"鼯鼠",img:"ws.png"},
    {id:41,name:"小冯",img:"xf.png"},
    {id:42,name:"烟鬼",img:"yg.png"},
    // ===== 紫卡 =====
    {id:43,name:"艾比达",img:"abd.png"},
    {id:44,name:"阿布萨罗姆",img:"abslm.png"},
    {id:45,name:"阿金",img:"aj.png"},
    {id:46,name:"波尔西",img:"bex.png"},
    {id:47,name:"巴利",img:"bl.png"},
    {id:48,name:"贝拉米",img:"blm.png"},
    {id:49,name:"长环岛路飞",img:"chdlf.png"},
    {id:50,name:"多尔顿",img:"ded.png"},
    {id:51,name:"二指",img:"ez.png"},
    {id:52,name:"福克西",img:"fkx.png"},
    {id:53,name:"甘福尔",img:"gfe.png"},
    {id:54,name:"盖蒙",img:"gm.png"},
    {id:55,name:"霍古巴克",img:"hgbk.png"},
    {id:56,name:"佳妮法",img:"jnf.png"},
    {id:57,name:"卡巴奇",img:"kbq.png"},
    {id:58,name:"克洛",img:"kl.png"},
    {id:59,name:"路飞",img:"lf.png"},
    {id:60,name:"里奇船长",img:"lqcz.png"},
    {id:61,name:"mr3",img:"mr3.png"},
    {id:62,name:"mr5",img:"mr5.png"},
    {id:63,name:"娜美",img:"nm.png"},
    {id:64,name:"佩鲁恰卡",img:"plqk.png"},
    {id:65,name:"乔巴",img:"qb.png"},
    {id:66,name:"情人节",img:"qrj.png"},
    {id:67,name:"萨蒂",img:"sd.png"},
    {id:68,name:"圣诞节",img:"sdj.png"},
    {id:69,name:"索隆",img:"sl.png"},
    {id:70,name:"山治",img:"sz.png"},
    {id:71,name:"塔希米",img:"txm.png"},
    {id:72,name:"乌索普",img:"wsp.png"},
    {id:73,name:"薇薇",img:"ww.png"},
    {id:74,name:"小八",img:"xb.png"},
    {id:75,name:"小红发",img:"xhf.png"},
    {id:76,name:"拉杰",img:"lj.png"},
    {id:77,name:"大剑",img:"dj.png"},
    {id:78,name:"斧头",img:"ft.png"},
    {id:76,name:"强高",img:"qg.png"},
    {id:77,name:"帕迪",img:"pd.png"},
    {id:78,name:"克比",img:"kb.png"},
    {id:79,name:"卓夫",img:"zf.png"},
    {id:80,name:"拉邦",img:"lb2.png"},
    {id:81,name:"功夫海牛",img:"gfhn.png"},
    {id:82,name:"古雷娃",img:"glw.png"},
    {id:83,name:"涅槃",img:"np.png"},
    {id:84,name:"和平主义者",img:"hpzyz.png"},
    {id:85,name:"阿悟",img:"aw.png"},
    {id:86,name:"拉斐特",img:"lft.png"},
    {id:87,name:"科尼丝",img:"kns.png"},
    {id:88,name:"罗拉",img:"ll.png"},
    {id:89,name:"伊格拉姆",img:"yglm.png"},
    {id:90,name:"斯潘达姆",img:"spdm.png"},
    {id:91,name:"摩根",img:"mg.png"},
    {id:92,name:"里奇",img:"lq.png"}
];

const SUPPORT_MAX_NUM = 4;
// 单轮限时20秒
const COUNTDOWN_SEC = 30;
// 蓝方全局已用援护（跨对局）
const BLUE_USED_SUPPORT = [];
// 红方全局已用援护（跨对局）
const RED_USED_SUPPORT = [];